------------------------------------- TABLES FOR NEW SYSTEM DATA -------------------------------------

CREATE TABLE IF NOT EXISTS company_user (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login varchar(255) NOT NULL,

    CONSTRAINT company_user_pkey PRIMARY KEY (id),
    CONSTRAINT company_user_uniq_login UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS patient_profile (
     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     first_name varchar(255) NULL,
     last_name varchar(255) NULL,
     status_id int2 NOT NULL,

     CONSTRAINT patient_profile_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS patient_note (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_date_time timestamp NOT NULL,
    last_modified_date_time timestamp NULL,
    note varchar(4000) NULL,
    created_by_user_id int8 NULL,
    last_modified_by_user_id int8 NULL,
    comment_id uuid NULL,
    patient_id int8 NOT NULL,

    CONSTRAINT patient_note_pkey PRIMARY KEY (id),
    CONSTRAINT fk_pat_note_to_modifyed_user FOREIGN KEY (last_modified_by_user_id) REFERENCES company_user(id),
    CONSTRAINT fk_pat_note_to_created_user FOREIGN KEY (created_by_user_id) REFERENCES company_user(id),
    CONSTRAINT fk_pat_note_to_patient FOREIGN KEY (patient_id) REFERENCES patient_profile(id)
);

CREATE TABLE IF NOT EXISTS old_client_mapping (
    id uuid NOT NULL,
    patient_id int8 NOT NULL,

    CONSTRAINT old_client_map_pkey PRIMARY KEY (id),
    CONSTRAINT fk_old_client_to_patient FOREIGN KEY (patient_id) REFERENCES patient_profile(id)
);

TRUNCATE TABLE company_user CASCADE;
TRUNCATE TABLE patient_profile CASCADE;
TRUNCATE TABLE patient_note CASCADE;
TRUNCATE TABLE old_client_mapping CASCADE;


------------------------------------- TABLES FOR OLD SYSTEM DATA -------------------------------------

CREATE TABLE IF NOT EXISTS agency (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,

    CONSTRAINT agency_pkey PRIMARY KEY (id),
    CONSTRAINT agency_uniq_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS old_client (
    id uuid NOT NULL,
    first_name varchar(255) NULL,
    last_name varchar(255) NULL,
    status varchar(255) NOT NULL,
    birth_date timestamp NOT NULL,
    created_at timestamp NOT NULL,
    agency_id int8 NOT NULL,

    CONSTRAINT old_client_pkey PRIMARY KEY (id),
    CONSTRAINT fk_old_client_to_agency FOREIGN KEY (agency_id) REFERENCES agency(id)
);

CREATE TABLE IF NOT EXISTS comment (
    id uuid NOT NULL,
    comment varchar(4000) NULL,
    created_at timestamp NOT NULL,
    modified_at timestamp,
    logged_user varchar(255) NOT NULL,
    client_id uuid NOT NULL,

    CONSTRAINT comment_pkey PRIMARY KEY (id),
    CONSTRAINT fk_comment_to_old_client FOREIGN KEY (client_id) REFERENCES old_client(id)
);

TRUNCATE TABLE agency CASCADE;
TRUNCATE TABLE old_client CASCADE;
TRUNCATE TABLE comment CASCADE;